wikimedia/html-metadata

README.md
index.js
package.json

* Add wrapper around microdata-node library.
* Fix bug in scrapeDublinCore which used the Cheerio instance
in memory rather the one passed through callback.
* Remove unwritten methods.
* Fill out readme file.

Wrap Jan's Schema.org microdata library & fixes

---

package.json

package.json: Fix licence name (ISC -> MIT)

---

index.js
package.json
test_files/turtle_article.html
test_files/turtle_movie.html
test_files/turtles.html

Switches to a native open graph implementation
Differences from previous implementation:
* Includes values from item types (i.e.
'article' namespace if value of og:type
is 'article'.
* Doesn't read custom namespaces or verticals
All item type properties are top-level.

Switch to Native Open Graph implementation

---

.gitignore
.jshintignore
.jshintrc
index.js
package.json
test/index.js

This PR fixes some minor code issues and adds a `.gitignore` file. Furthermore, it adds a simple test suite using [mocha](https://github.com/mochajs/mocha) and code coverage via [istanbul](https://github.com/gotwarlost/istanbul):
* `npm test` runs the tests
* `npm run-script coverage` runs the tests and reports code coverage
Note that currently there are only two tests: a `jshint` check and a superficial test downloading an article with meta-data, parsing it using `parseOpenGraph` and checking if some fields are present in the response. Needless to say, this should be considered only the beginning - we should develop more tests (at least one for each exported function), and also be more strict (tests should check corner cases as well as common use-cases).

Some minor fixes + a simple test suite

---

index.js
package.json
test/index.js

Non open graph tags were being added in
some cases, because indexOf returns -1
for items not in the list and code was
assuming a non-number value.
Added case in test for this in test/index.js
as this was where issue was initially detected.
Partially addresses issue #16.

Prevent non-og tags from being added

---

index.js
package.json
test/static.js
test_files/turtle_article.html
test_files/turtle_movie.html

Previously, subproperties were added to whatever
root was created directly before them. Now checks to
make sure the subproperty names match, e.g.
og:image:width only gets added to the most recent
og:image and not og:audio.
Also switched from overwriting latest sub-subproperty e.g.
og:image:width to keeping first og:image:width added.
Added bad data to test_files and, and added tests
of those files to verify that data is correctly
added.
Issue #16

Always add subproperties to the correct root

---

README.md
index.js
lib/index.js
package.json
test/errors.js
test/scraping.js

The release of 1.0.0 broke backwards compatibility
by replacing all callbacks with Promises; this
change restores the ability to use all previous
functions like callbacks and retains the ability
of 1.0.0 to use these functions like Promises.
Minor fixes to tests which have broken following
changes in metadata at the given urls.

Make library compatible with callbacks

---

test/scraping.js

The expected value for the image url in the open graph scraping test changed upstream;
update so it passes tests.

Update test to reflect updated image url at source

---

test/scraping.js

* Eliminate duplicate requests for the same
resource
* Use direct object comparison instead of
stringify comparison (fixes erroneously passing
test.)
* Other minor fixes

Clean up scraping tests

---

lib/index.js
package.json

preq v0.5.1 contained a subtle bug where the client had to provide the `uri` property instead of `url`. The new version fixes that.

Bump preq to v0.5.2 and release v1.6.2

---

lib/index.js
package.json
test/errors.js
test/scraping.js
test/static/turtle_article_errors.html

Previously, metadata with tags that were missing content
were being added, resulting in keys with the value
'undefined.' This skips adding tags with missing
values.
Adds static and live test.
Addresses issue #54

Don't add tags with missing content

---

test/scraping.js

* Change language scraping test to lemonde.fr
as the hu site now uses xml:lang instead of
lang. TODO: investigate xml:lang.
* Apparently jsonld.com stopped actually
having and jsonld in their page (???) so
remove that site from being checked.
* Fortune.com no longer provides the author
in their open graph metadata :/
* Afposten added an additional field to
their Twitter metadata

Fix failing tests due to upstream changes

---

lib/index.js
package.json
test/errors.js
test/scraping.js

* Update packages (preq, bluebird, mocha, cheerio)
* Fix name of test to be more descriptive
* Restore two tests that were previously failing due to website being
down
* Minor fix for cheerio update in jsonLd due to non-backwards
compatible changes

Updates packages, fix tests

---

index.js
lib/index.js
test/scraping.js
test/static.js

In my use case I've already downloaded the HTML files and needed to parse them locally.
So I exposed a function `loadHTML` that takes the html as string and then internally converts it into cheerio object.
Here is usage example: 
```
const html = fs.readFileSync('./page.html', 'utf-8');
scrape.loadHTML(html).then(function(metadata){
console.log(JSON.stringify(metadata, null, 4));
});
```

Exposed loadHTML method

---

README.md
lib/index.js
test/scraping.js
test/static.js
test/static/turtle_article.html
test/static/turtle_article.json
test/static/turtle_article_case.html

This fetches the `dir` (e.g. "rtl") attribute from the `<html>` tag.

Fetch the direction metadata from <html> tag

---

package-lock.json
package.json
test/scraping.js

This is to fix issue #95 
I modified the `scraping.js` file to use more browser-like User-Agent and Accept headers. Here are the key changes:
1. Added constants for user agent and accept header:
```javascript
const userAgent = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36';
const acceptHeader = 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8';
* Created a `getWithHeaders` function to make requests with these headers:
```javascript
function getWithHeaders(url) {
return preq.get({
uri: url,
headers: {
'User-Agent': userAgent,
'Accept': acceptHeader
}
});
}
```
* Updated all `preq.get()` calls to use `getWithHeaders()` instead.
* Modified the `meta()` function calls to include the headers: …
```

updating scraping.js to fix HTTP 406 error while runing the test suite

---

.eslintrc.json
.github/workflows/node.js.yml
index.js
lib/index.js
package-lock.json
package.json
test/errors.js
test/index.js
test/parsing.js
test/scraping.js
test/static.js
test/static/turtle_article.json
test/static/turtle_movie.json
test/utils/assert.js

* Add linting and fix files accordingly.
* Remove jshint as covered by eslint.
* Replace assert with chai in line with other
wmf node packages.
* Require node >= 16 and release major version.

Add linting

---

package-lock.json
package.json

Pin cheerio to 1.0.0-rc.12 as 1.0.0 requires node >= 18

Update and pin cheerio version

---

.github/workflows/node.js.yml
package-lock.json
package.json

Require node >= 18, in preparation
for removing the deprecated preq library
and replacing it with native fetch, released
in node 18.
Remove testing for node >= and add testing
for node 20 and 22.
Rename master branch to main in ci as this
is now the default branch name.
Bug: T361602

Remove support for node <18

---

test/errors.js
test/scraping.js

Replaces preq with fetch in tests.
Requires node >= 18
Bug:  T361602

Replace preq with fetch in tests

---

README.md
index.js
package-lock.json
package.json
test/scraping.js

Remove preq from library entirely and
replace with native fetch.
This is not backwards compatible if third
party users are a) using the parseAll function,
and b) other features of preq, such as
the internalUri parameter or wrapped errors;
see https://github.com/wikimedia/preq for more
details on how preq alters the Response
object.
Bug: T361602

[BREAKING CHANGE] Remove preq from library

---

README.md
index.js
package.json

Bluebird Promises provides support for nodeifying this library. However bluebird library use is now discouraged in favour of native Node Promises. In preparation for removing this library and switching to native JS Promises, remove support for callback style requests.
Increment package.json to 3.0.0 to go along with documentation, but not ready for release yet, as this release is planned to remove the bluebird library entirely.

[BREAKING CHANGE] Remove support for callback (node-style) requests

---

package-lock.json
package.json
test/static.js
test/static/turtle_article.html
test/static/turtle_article.json
test/static/turtle_article_case.html

Addresses #83 and #68 
* Add tests for schema.org microdata. 
* Clean up static html files a bit by adding more comments and indenting.

build: update microdata-node and add tests

---

.gitignore
package-lock.json
package.json

Replace istanbul with nyc package
as the istanbul npm repo is deprecated.
Only affects coverage tests.

Replace istanbul with nyc package

---

index.js
package-lock.json
package.json
test/scraping.js

* Type check was erroneously not finding uri
* Add tests for both with and without headers
* Add tests for await pattern
* Increment patch version
Fixes #121

Fix "no uri supplied in argument" error
